"""Original periodic material maps for inferred smooth flaking Platanus bark."""
from pathlib import Path
import json,hashlib,numpy as np
from scipy.ndimage import gaussian_filter,zoom
from PIL import Image
R=Path(__file__).resolve().parents[1];D=R/'derived/materials/platanus_flaking';D.mkdir(parents=True,exist_ok=True);rng=np.random.default_rng(119962);N=4096
def noise(size,sigma):
 x=gaussian_filter(rng.standard_normal((size,size)).astype(np.float32),sigma,mode='wrap');x/=x.std()
 return zoom(x,N/size,order=3,mode='grid-wrap',grid_mode=True).astype(np.float32)
field=noise(256,9)+.34*noise(256,3.8)+.12*noise(512,2.2)
palette=np.array([[125,129,109],[162,160,133],[192,186,162],[148,151,127],[180,176,149]],dtype=np.float32)/255
thresholds=[-1.00,-.20,.70,1.42];color=np.broadcast_to(palette[0],(N,N,3)).copy();height=np.zeros((N,N),np.float32)
for i,t in enumerate(thresholds):
 a=np.clip((field-t)/.035+.5,0,1);a=a*a*(3-2*a);color=color*(1-a[:,:,None])+palette[i+1]*a[:,:,None];height+=a*.00011
grain=noise(1024,.75);striations=noise(1024,(5,.65));variation=.012*grain+.010*striations
color=np.clip(color+variation[:,:,None],0,1);rough=np.clip(.80+.022*grain+.04*np.tanh(field),.65,.95)
height+=grain*.000018;spacing=2.4/N;dx=(np.roll(height,-1,axis=1)-np.roll(height,1,axis=1))/(2*spacing);dy=(np.roll(height,-1,axis=0)-np.roll(height,1,axis=0))/(2*spacing)
normal=np.stack([-dx,dy,np.ones_like(dx)],axis=-1);normal/=np.linalg.norm(normal,axis=-1)[:,:,None]
files=[]
for name,arr in [('albedo',color),('roughness',rough),('normal_gl',normal*.5+.5)]:
 p=D/(name+'.png');Image.fromarray(np.uint8(np.clip(arr*255,0,255))).save(p,compress_level=6);files.append({'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(D/'receipt.json').write_text(json.dumps({'creator':'Original procedural surface generated by project code','kind':'inferred biological material, not a local tree scan or copied photograph','physical_tile_size_m':2.4,'resolution':[N,N],'seed':119962,'files':files},indent=2),encoding='utf-8')
print(json.dumps({'material':str(D),'files':len(files),'resolution':N,'source':'original procedural inference'}))
