"""Images below have actually been viewed; retain visible failures explicitly."""
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];V='G1_013r2';E=R/'evidence'/V;names=['BE_QA_SOUTH_APPROACH','BE_QA_SOUTH_FACILITIES','BE_QA_SOUTH_WALK']
review={'version':V,'images_actually_inspected':[{'file':n+'.png','sha256':hashlib.sha256((E/(n+'.png')).read_bytes()).hexdigest()} for n in names],
 'comparisons':['G1_013/BE_QA_SOUTH_APPROACH.png','G1_013/BE_QA_SOUTH_WALK.png','G1_013/BE_QA_SOUTH_TREE_BASE.png','G1_013r1/BE_QA_SOUTH_FACILITIES.png','G1_013r1/BE_QA_SOUTH_APPROACH.png'],
 'observed_improvements':['The continuous AV3573 footway, physical curb and tree soils replace photographic ground in the actual footprint. Existing building hole is retained.','Two separate plane trees have rooted collars and individual branch structures at source XY/height. Their old near crown sheets were reduced after same-camera inspection and bounded neighboring-tree partition.','Own-source masts, paired notice frames and DFI replace protected photo-device columns; the bin has a real side aperture, closed sloping lid and dark inner liner.','Strong vertical fake highlight boundary in the first bin disappeared after radial split normals and restrained metre-scale ground-steel roughness. Information faces remain readable.'],
 'limitations':['AV3573 is NOT visually accepted: large unrebuilt source tree/canopy masses, floating fragments and the central pavilion remain visibly broken in the walk view.','The pale flat area is the real building plan hole above an unfinished building context; filling it as footway would falsify the site.','Ten of twelve inventory trees and remaining source facilities are not rebuilt. Adjacent photo-boundary artifacts remain.','Source tree positions/species/heights are known; individual crown/roots/bark/ground detail inferred. Canopy cleanup partitions are not surveyed crown footprints.','Info74/88 subtype mapping and exact anchor semantics unresolved. DFI fabrication proxy has no live timetable. Manufacturer110L bin is an inferred variant, not a confirmed local110L installation.','Footway grade, curb profiles, ramps and finishes are inferred and are not accessibility acceptance.','No realtime or natural-use acceptance. CUA retry still returned browsers empty and nodeRepl.fetch failed; MCP solid viewport is not counted as a material render.'],
 'accepted':False,'full_G1_complete':False}
(E/'native_visual_review.json').write_text(json.dumps(review,indent=2));print(json.dumps({'version':V,'images_seen':len(names),'accepted':False}))
